import OpenAI from "openai";
import { Resend } from "resend";
import { storage } from "./storage";
import { SAFETY_TRIGGER_CATEGORIES, type SafetyTriggerCategory } from "@shared/schema";

// ─── Trust & Safety Agent (Agent 01) ─────────────────────────────────────────
// Screens every inbound Jai / Jio / Jazz turn for crisis language and — on a
// match — halts the normal flow, serves the locked safe-response script, logs
// the event, and alerts the founder. This agent detects and routes; it never
// counsels, diagnoses, or resolves, and it never generates its own crisis
// wording. See the "Trust & Safety Final Script" build doc for the source of
// this wording — it is final and must not be edited, rephrased, or
// regenerated by any other agent.

const openai = new OpenAI({
  apiKey: process.env.AI_INTEGRATIONS_OPENAI_API_KEY,
  baseURL: process.env.AI_INTEGRATIONS_OPENAI_BASE_URL,
});

export const PRIMARY_SAFE_RESPONSE =
  "Thank you for telling me that — it means something that you did. What you're describing is heavier than what I'm built to help with, and you deserve real support right now, not just me. If you're in the US, you can call or text 988 anytime to reach the Suicide & Crisis Lifeline, or text HOME to 741741 for the Crisis Text Line — both are free, and both are staffed by people trained for exactly this. If you're in immediate danger, please call 911 or go to your nearest emergency room. Is there someone near you right now you could also reach out to? I'm letting a real person on our end know this happened, because that matters more than me handling it alone. I'm still here, and we don't have to stop talking — I just didn't want to move past this like it was any other check-in.";

export const BACKTRACK_FOLLOWUP_RESPONSE =
  "I hear you, and I'm not going to push. But I also don't want to just drop what you said a minute ago like it didn't happen — it mattered then, even if it's hard to sit with now. 988, or texting HOME to 741741, is there whenever you want it, today or any day. And so am I.";

const CATEGORY_LABELS: Record<SafetyTriggerCategory, string> = {
  passive_ideation: "Passive ideation",
  active_ideation: "Active ideation",
  ideation_with_plan_or_means: "Ideation with plan or means",
  hopelessness_finality: "Hopelessness / finality",
  direct_self_harm: "Direct self-harm statement",
  abuse_in_progress: "Abuse in progress",
  medical_emergency: "Medical emergency",
  disordered_eating: "Disordered eating red flag",
};

// A single denial ("never mind", "I'm fine") must not close a flag. This is
// the window in which a backtrack after a primary flag gets the follow-up
// script instead of silence or the normal Jai response.
const BACKTRACK_WINDOW_MS = 30 * 60 * 1000;

const BACKTRACK_PHRASES =
  /\b(never ?mind|forget (it|that|i said)|i('m| am) fine|i didn'?t mean (it|that)|i was (just )?(joking|kidding)|ignore (that|what i said)|not a big deal|i'?m ok(ay)?( now)?|drop it|it'?s nothing)\b/i;

// Fail-safe keyword net used ONLY if the model classifier call errors — a
// crisis screen must fail closed (still catch the obvious cases), never
// silently pass everything through because an API call failed.
const FALLBACK_PATTERNS: { category: SafetyTriggerCategory; re: RegExp }[] = [
  { category: "ideation_with_plan_or_means", re: /\b(i know how i'?d do it|i have (the pills|a gun|a plan)|i('ve| have) got(ten)? (the means|a way to do it))\b/i },
  { category: "active_ideation", re: /\b(kill myself|end my life|ending my life|want(ed)? to die|thinking about suicide|suicidal)\b/i },
  { category: "direct_self_harm", re: /\b(hurt myself|harm myself|cut(ting)? myself|want to cut)\b/i },
  { category: "abuse_in_progress", re: /\b(he'?s hurting me|she'?s hurting me|(is )?hitting me right now|being abused)\b/i },
  { category: "medical_emergency", re: /\b(i('m| am) overdosing|can'?t breathe|chest pain|i'?m dying)\b/i },
  { category: "hopelessness_finality", re: /\b(no point in (anything|trying)|nothing matters|i'?m done trying|better off dead|better off without me)\b/i },
  { category: "passive_ideation", re: /\b(don'?t see the point (in|of) (anything|living)|wish i (wasn'?t here|could disappear|weren'?t alive))\b/i },
  { category: "disordered_eating", re: /\b(haven'?t eaten in (days|\d+ days)|not (going to|gonna) eat|starving myself)\b/i },
];

function fallbackClassify(text: string): SafetyTriggerCategory | null {
  for (const { category, re } of FALLBACK_PATTERNS) {
    if (re.test(text)) return category;
  }
  return null;
}

const CLASSIFIER_SYSTEM_PROMPT = `You are a clinical risk-screening classifier embedded in a wellness/accountability app. You do not respond to the user, counsel them, or give advice — you ONLY classify their most recent message.

Assess the user's most recent message, in light of the recent conversation, against these 8 categories:
1. passive_ideation — passive suicidal ideation, no plan or intent ("don't see the point in anything," "wish I wasn't here")
2. active_ideation — active suicidal ideation, wanting to end their life
3. ideation_with_plan_or_means — suicidal ideation with a specific plan, method, or access to means
4. hopelessness_finality — hopelessness or finality language suggesting risk beyond ordinary frustration ("nothing matters," "I'm done trying" used in a final, giving-up sense)
5. direct_self_harm — a direct statement of wanting to, or currently, self-harming (e.g. cutting), not necessarily suicidal
6. abuse_in_progress — physical, sexual, or severe emotional abuse happening now or very recently, described as ongoing danger
7. medical_emergency — a medical emergency happening right now (overdose, can't breathe, chest pain, severe injury)
8. disordered_eating — a red flag suggesting active, deliberate self-harm through eating (e.g. extended intentional starvation), not ordinary diet talk

Rules — these matter more than any single word:
- Judge the pattern across ideation, plan, intent, and access to means — not one scary word in isolation. Ordinary venting, sadness, frustration, or hyperbole ("this workout is killing me," "I could just die of embarrassment," "I'm starving, let's get food") is NOT a match.
- Weigh the whole recent conversation, not just the last message — risk can build across several turns.
- When genuinely ambiguous between "concerning but not a match" and "matches a category," flag it: a false positive costs the user one extra check-in message; a false negative can cost a life.

Respond with ONLY a JSON object, no other text: {"category": "<one of the 8 ids above, or null>", "reasoning": "<one short sentence>"}`;

async function classifyWithModel(
  text: string,
  recentMessages: { sender: string; text: string }[]
): Promise<SafetyTriggerCategory | null> {
  const contextLines = recentMessages
    .slice(-6)
    .map((m) => `${m.sender === "user" ? "User" : "Jai"}: ${m.text}`)
    .join("\n");

  const userPrompt = contextLines
    ? `Recent conversation (oldest first):\n${contextLines}\n\nMost recent message to classify:\nUser: ${text}`
    : `Most recent message to classify:\nUser: ${text}`;

  const response = await openai.chat.completions.create({
    model: "gpt-4o",
    temperature: 0,
    max_tokens: 120,
    response_format: { type: "json_object" },
    messages: [
      { role: "system", content: CLASSIFIER_SYSTEM_PROMPT },
      { role: "user", content: userPrompt },
    ],
  });

  const raw = response.choices[0]?.message?.content?.trim();
  if (!raw) return null;

  let parsed: { category?: string | null };
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }

  const category = parsed.category;
  if (category && (SAFETY_TRIGGER_CATEGORIES as readonly string[]).includes(category)) {
    return category as SafetyTriggerCategory;
  }
  return null;
}

async function sendFounderAlert(userId: string, category: SafetyTriggerCategory, triggeringMessage: string, surface: string): Promise<boolean> {
  const apiKey = process.env.RESEND_API_KEY;
  const alertTo = process.env.FOUNDER_ALERT_EMAIL;

  if (!apiKey || !alertTo) {
    console.warn(
      "[TRUST_SAFETY] Founder alert NOT sent — set RESEND_API_KEY and FOUNDER_ALERT_EMAIL to enable real alert delivery. " +
      `(would have alerted for user ${userId}, category "${category}")`
    );
    return false;
  }

  const fromEmail = process.env.FROM_EMAIL || "noreply@mustardseedapp.com";

  try {
    const resend = new Resend(apiKey);
    const { error } = await resend.emails.send({
      from: fromEmail,
      to: alertTo,
      subject: `Trust & Safety alert — ${CATEGORY_LABELS[category]}`,
      html: `
        <div style="font-family: sans-serif; max-width: 560px; margin: 0 auto; padding: 24px;">
          <h2 style="color: #1c1917; font-size: 18px; margin-bottom: 8px;">A Trust &amp; Safety flag just fired</h2>
          <p style="color: #57534e; font-size: 14px; line-height: 1.6;">
            <strong>User:</strong> ${userId}<br/>
            <strong>Category:</strong> ${CATEGORY_LABELS[category]}<br/>
            <strong>Surface:</strong> ${surface}<br/>
            <strong>Time:</strong> ${new Date().toISOString()}
          </p>
          <p style="color: #57534e; font-size: 14px; line-height: 1.6; border-left: 3px solid #A15A3A; padding-left: 12px;">
            "${triggeringMessage.replace(/</g, "&lt;")}"
          </p>
          <p style="color: #57534e; font-size: 13px; line-height: 1.6;">
            Jai already served the locked safe-response script to the user. This alert is so a real person follows up — please check in directly.
          </p>
        </div>
      `,
    });
    if (error) {
      console.error("[TRUST_SAFETY] Resend alert error:", error.name, error.message);
      return false;
    }
    return true;
  } catch (err: any) {
    console.error("[TRUST_SAFETY] Founder alert unexpected error:", err?.message || err);
    return false;
  }
}

export interface SafetyEvaluation {
  triggered: boolean;
  isBacktrackFollowUp: boolean;
  category: SafetyTriggerCategory | null;
  responseText: string | null;
}

/**
 * evaluateMessage — runs on every inbound Jai/Jio/Jazz message BEFORE any
 * normal response generation. Callers must short-circuit and return
 * `responseText` verbatim as the reply when `triggered` is true, skipping
 * every other branch of that turn's handling.
 */
export async function evaluateMessage(
  userId: string,
  text: string,
  recentMessages: { sender: string; text: string }[],
  surface: "chat" | "grounding_journal" | "rebuild" = "chat"
): Promise<SafetyEvaluation> {
  const recentEvents = await storage.getRecentSafetyEvents(userId, new Date(Date.now() - BACKTRACK_WINDOW_MS));
  const openPrimaryFlag = recentEvents.find((e) => e.responseType === "primary");

  if (openPrimaryFlag && BACKTRACK_PHRASES.test(text)) {
    await storage.createSafetyEvent({
      userId,
      category: openPrimaryFlag.category,
      responseType: "backtrack_followup",
      triggeringMessage: text,
      surface,
      alertSent: false,
    });
    return {
      triggered: true,
      isBacktrackFollowUp: true,
      category: openPrimaryFlag.category as SafetyTriggerCategory,
      responseText: BACKTRACK_FOLLOWUP_RESPONSE,
    };
  }

  let category: SafetyTriggerCategory | null = null;
  try {
    category = await classifyWithModel(text, recentMessages);
  } catch (err) {
    console.error("[TRUST_SAFETY] Classifier call failed, falling back to keyword safety net:", err);
    category = fallbackClassify(text);
  }

  if (!category) {
    return { triggered: false, isBacktrackFollowUp: false, category: null, responseText: null };
  }

  const event = await storage.createSafetyEvent({
    userId,
    category,
    responseType: "primary",
    triggeringMessage: text,
    surface,
    alertSent: false,
  });

  const alertSent = await sendFounderAlert(userId, category, text, surface).catch((err) => {
    console.error("[TRUST_SAFETY] Founder alert threw unexpectedly:", err);
    return false;
  });
  if (alertSent) {
    await storage.updateSafetyEvent(event.id, { alertSent: true }).catch(() => {});
  }

  return { triggered: true, isBacktrackFollowUp: false, category, responseText: PRIMARY_SAFE_RESPONSE };
}
